<a href="https://colab.research.google.com/github/DARoSLab/Adv_robot_dyn_ctrl/blob/main/Lectures/Lecture5_orientation_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [11]:
# make 3 x 3 numpy matrix
rot_45_x = np.array([[1, 0, 0],
                     [0, np.cos(np.deg2rad(45)), -np.sin(np.deg2rad(45))],
                     [0, np.sin(np.deg2rad(45)), np.cos(np.deg2rad(45))]])
rot_30_y = np.array([[np.cos(np.deg2rad(30)), 0, np.sin(np.deg2rad(30))],
                     [0, 1, 0],
                     [-np.sin(np.deg2rad(30)), 0, np.cos(np.deg2rad(30))]])


In [12]:
print(rot_45_x)
print(rot_30_y)

[[ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]
 [ 0.          0.70710678  0.70710678]]
[[ 0.8660254  0.         0.5      ]
 [ 0.         1.         0.       ]
 [-0.5        0.         0.8660254]]


In [13]:
rot_mtx = rot_45_x @ rot_30_y
print(rot_mtx)

[[ 0.8660254   0.          0.5       ]
 [ 0.35355339  0.70710678 -0.61237244]
 [-0.35355339  0.70710678  0.61237244]]
